wallet_mnemonic: "rebel wet poet torch carpet gaze axis ribbon approve depend inflict menu"
chain:
  id: cudos-local-network
  rpc: http://127.0.0.1:26657
  grpc: 127.0.0.1:9090
tokenised_infra_url: http://127.0.0.1:8080
state_file: state.json
max_retries: 10
retry_interval: 30s
relay_interval: 5s
payment_denom: acudos