version: '3.6'
services:
  cudos-ondemand-minting-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
        max-file: "16"
